name: 'build abook template'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amane/lualatex-latexmk:2024.1
    steps:
    - uses: actions/checkout@v1
    - name: compile document
      run: |
        ./script/make_story_list.sh
        llmk book.tex
    - name: upload document
      uses: actions/upload-artifact@v7
      with:
        path: build/book.pdf
        archive: false
